worker_processes ${{NUM_WORKERS}};
error_log stderr notice;
daemon off;
pid logs/nginx.pid;
pcre_jit on;
events {
  worker_connections 1024;
}

http {
  include mime.types;

  init_by_lua_block {
    require "lpeg"
  }

  # data caching
  lua_shared_dict page_cache 512m;
  # put these all in one spot (that isn't the root dir, because i'm petty)
  fastcgi_temp_path .temp/fastcgi 1 2;
  proxy_temp_path .temp/proxy 1 2;
  scgi_temp_path .temp/scgi 1 2;
  uwsgi_temp_path .temp/uwsgi 1 2;
  client_body_temp_path .temp/client_body 1 2;
	server_tokens off;
	sendfile on;

  server {
    listen ${{PORT}};

    lua_code_cache ${{CODE_CACHE}};

    location / {
      default_type text/html;
      content_by_lua_block {
          require("lapis").serve("app")
      }
    }

    location /static/ {
      alias static/;
    }

    location /favicon.ico {
      alias static/favicon.ico;
    }

    location /robots.txt {
      alias static/robots.txt;
    }
    # if ya don't listen
    if ($http_user_agent ~* "${{botlist}}") {
      return 307 https://ash-speed.hetzner.com/1GB.bin;
    }

  }
}
